### ISSUE TITLE
'resman: command not found'

### ISSUE THREAD

**Issue by GaryGao829** [uber-research/deconstructing-lottery-tickets#1]
Dear Uber developers,

I've read both your blog and paper. It's quite high-quality and inspiring work. I want to run the related code in this repo. However, I met the error: 'resman: command not found' in the 2 shell files. I searched online, there's little useful information. 
I want to ask on which environment you run this shell command. Is it available to install the 'resman' on Linux? 

Thanks

**Comment by hlml** [comment]
Hello, you can install the resman package here: https://github.com/yosinski/GitResultsManager
